### ISSUE TITLE
Investigate pro-hosted squarespace vs wp.com solutions.

### ISSUE THREAD

**Issue by conoramurphy** [CoderDojo/coolest-platform#149]
### Business Case

Limiting what changes we allow to cp.com allows up to ship fast and more confidently etc.

### Investigate the pro-hosted solutions

So we need to investigate the wp.com vs Squarespace solutions. In particular but not exhaustively

 - [ ] Can we keep a flat site as home and redirect the rest of the site to them. (Not 100% necessary but would speed it up a lot)
 - [ ] Which ones easier to set up and a little bit flexible
 - [ ] Check with Rich once the first two are filled out that he can do the basic needs in it.

**Comment by conoramurphy** [comment]
Update: There's no neat way to keep the flat site as homepage
- Either we use a sub url "pages.etc" for the site
- Or we move the homepage into the service (which would probably mean WordPress)

Might need to set up a theme in either and move the homepage in. Gonna grab rich and go over options with him and try to make a decision in the next 2 hours.

**Comment by damienh** [comment]
Ok so having hit issues with having a wordpress hosted & coolestprojects.org static page I spoke with @grega about what are options are regarding other wordpress hosting options.

1. [WPEngine](https://my.wpengine.com)
This service offers us the most flexibility when it comes to managing a wordpress instance. dev, staging and production environments and the ability to deploy via a git origin. This would make working with the contractor easier and means we can utilise version control and deployment. 

In terms of domains we can use a `CNAME` like `blog.coolestprojects.org` and then use the CloudFlare worker to mask it.

2. Additional domain
Greg noted that we could simply purchase an additional domain for the blog to live at e.g. `coolestprojectsblog.org`. This would be used to house the domain on wordpress.com. Requests to it would be masked by the CloudFlare worker as if its serving `coolestprojects.org`

3. [Digital Ocean](https://www.digitalocean.com/docs/one-clicks/wordpress/)
We could use DO one click wordpress installation which would allow us to get started quickly, however we would need do additional work to allow for the environment to be managed via puppet like we do with our CodeClub DO instances. It would also need a deployment flow working out.

**Recommendation** 
I think using WPEngine is the best option. This is because it will allow us to scale down the line. It also matches a deployment flow we already use. 

If all that fails we can simply go with option 2 and buy a domain.

**Comment by conoramurphy** [comment]
Thanks. This clarifies things.

I'm good with WPEngine. Also nice timing with new wp editing interface Gutenberg, WPEngine is launching it in a day which makes WP much nicer for non-devs to create pages in. 

_(side note We should have formalised the discussion here earlier rather than constantly jumping on calls, my fault!)_

**Comment by Wardormeur** [comment]
Not sure how 2) works to solve the issue with the web worker being unable to query a NS.
1) still needs to be tested out to see if it works, but the docs seems to inform it should (https://wpengine.com/support/cloudflare-best-practices/)

**Comment by Wardormeur** [comment]
Can we close now ? That seems fairly engaged into WPEngine

**Comment by conoramurphy** [comment]
yep good to close from me.
