### ISSUE TITLE
Suggestion: Registration page copy (group vs. individual) 

### ISSUE THREAD

**Issue by Christinafoust** [CoderDojo/coolest-platform#185]
Got feedback that page 1 registration can be confusing for groups. 

the 2nd bullet point says " Only one person should register per project."
- it implies that groups may not be able to register. 

Can we modify to: "Only one person should register per project.(If you have a group project, choose a team leader)."

**Comment by mrichardson23** [comment]
Tweaking that suggestion a bit:

"Only one person should register per project. (If you have a group project, choose a team leader.)"

**Comment by conoramurphy** [comment]
Can I ask where was the feedback is from, multiple confused attendees or one or even internal feedback?

Also, I think the suggested text would likely confuse more as we never before or after have any concept of a team leader and plenty of parents/mentors register group projects etc. 
The awkwardness with this line is it has to clarify 4/5 quite different use cases without turning into an essay. (1 kid registering 1 project, 1 kid wanting to register 2 of their own projects (no allowed), your case, mentors/parents registering groups and multiple projects).

I don't think this line is perfect at all and obviously, if we have evidence this is the serious issue we'll have to work on the text a good bit to get it to a significantly better place. But if not we'll bias toward leaving 1/2 person confused rather than potentially confuse many more that currently register fine.

**Comment by mrichardson23** [comment]
Dana reviewed the platform for the first time today, so she was seeing it with fresh eyes. She pointed out that the copy sounded to her as though group projects wouldn't be eligible. There simply may not be a an ideal or elegant way to explain the situation, so I don't have an objection at all to leaving this alone.
