### ISSUE TITLE
Abstract custom questions in front-end

### ISSUE THREAD

**Issue by Wardormeur** [CoderDojo/coolest-platform#88]
### Business Case
Currently, the custom questions are set db-side, but hardcoded in the front-end.
That would avoid a rewrite of the front if the user needs different custom questions.

### Complications 
~~UK do not want any custom questions. Would it be possible to just skip that question if there are no Custom Questions for an event?~~

**Comment by Wardormeur** [comment]
@conoramurphy Do we have confirmation that every custom questions will go into into the extra details page ?

**Comment by Wardormeur** [comment]
Considering the actual question string for the question (the key "social_project" or "educational_project" is, not the sentence) is not saved in the backend, this is going to be a hardcoded list of switches for each known questions cross-instances...
Not the best solution, but this was designed originally with translations in mind and keys are better at that than sentences
I don't believe that changing the schema for that is a good idea by itself cc @damienh

**Comment by Wardormeur** [comment]
As a note @conor : usa's stipend and uk's bursary are basically the same. Could it be possible to merge them to avoid 2 very similar questions in a shared codebase ?

**Comment by Wardormeur** [comment]
PR in the meantime : 
https://github.com/CoderDojo/coolest-platform/pull/115 cc @damienh

**Comment by conoramurphy** [comment]
Adressing in order

_Do we have confirmation that every custom questions will go into the extra details page?_
Yes

_I don't believe that changing the schema for that is a good idea by itself_
Whatever is easiest to maintain

_ Did you attend Coolest Projects UK last year_
We can't solve this super easily because of data cleanliness, multiple projects per email, what you're matching on etc. Maybe once they've used the same form in multiple years?

_ USA's stipend and UK's bursary are basically the same. Can we merge_
We could merge the wording but the bursary link might be different which would make the merging pointless. Confirming that.
